name: reflector_dispatcher
description: A method introspector/invoker that can operate with a Reflectable class. Facilitates invoking an API for JSON-RPC server side implementation.
version: 1.0.1
repository: https://github.com/jwashin/reflector_dispatcher

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 rpc_exceptions: ^1.0.1
 rpc_dispatcher: ^1.0.1

dev_dependencies:
  build_runner: ^1.12.2
  reflectable: ^3.0.0
  pedantic: ^1.9.0
  test: ^1.14.4
